// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthResponse {
    /// "ok" when healthy. When paused, the RPC returns FAILED_PRECONDITION instead
    /// (not UNAVAILABLE, which is reserved for transport-level failures).
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetCaCertRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCaCertResponse {
    /// PEM-encoded CA certificate bytes.
    #[prost(bytes = "vec", tag = "1")]
    pub pem: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnforceRequest {
    #[prost(string, tag = "1")]
    pub subject: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub target: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub scenarios: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// When unset, the service uses its own current time.
    #[prost(message, optional, tag = "4")]
    pub now: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EnforceResponse {
    #[prost(bool, tag = "1")]
    pub allow: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReachableRequest {
    #[prost(string, tag = "1")]
    pub subject: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub scenarios: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReachableResponse {
    #[prost(string, tag = "1")]
    pub subject: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub reachable: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Condition {
    /// "ALL" or "TIME" (case-sensitive, matching the HTTP JSON wire format).
    #[prost(string, tag = "1")]
    pub kind: ::prost::alloc::string::String,
    /// TIME only: inclusive start of half-open [start, end). Unset = unbounded.
    #[prost(message, optional, tag = "2")]
    pub start: ::core::option::Option<::prost_types::Timestamp>,
    /// TIME only: exclusive end. Unset = unbounded.
    #[prost(message, optional, tag = "3")]
    pub end: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Binding {
    #[prost(string, tag = "1")]
    pub src: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub dst: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub scenario: ::prost::alloc::string::String,
    /// When unset on Add/Update, the service defaults to true (same as HTTP omit).
    #[prost(bool, optional, tag = "4")]
    pub enabled: ::core::option::Option<bool>,
    #[prost(message, repeated, tag = "5")]
    pub conditions: ::prost::alloc::vec::Vec<Condition>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListBindingsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListBindingsResponse {
    #[prost(message, repeated, tag = "1")]
    pub bindings: ::prost::alloc::vec::Vec<Binding>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBindingRequest {
    #[prost(string, tag = "1")]
    pub src: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub dst: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub scenario: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetEnabledRequest {
    #[prost(string, tag = "1")]
    pub src: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub dst: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub scenario: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub enabled: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetEnabledResponse {
    #[prost(bool, tag = "1")]
    pub ok: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveBindingRequest {
    #[prost(string, tag = "1")]
    pub src: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub dst: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub scenario: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RemoveBindingResponse {}
/// Generated client implementations.
pub mod rbac_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// RbacService mirrors the HTTP /v1 REST API (plus /healthz and /v1/ca-cert).
    #[derive(Debug, Clone)]
    pub struct RbacServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl RbacServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> RbacServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> RbacServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            RbacServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Health checks liveness. Returns FAILED_PRECONDITION when the service is
        /// paused (HTTP GET /healthz → 503). Transport failures use UNAVAILABLE and
        /// must not be confused with pause.
        pub async fn health(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rbac.v1.RbacService/Health",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rbac.v1.RbacService", "Health"));
            self.inner.unary(req, path, codec).await
        }
        /// GetCACert returns the PEM-encoded CA certificate (HTTP GET /v1/ca-cert).
        pub async fn get_ca_cert(
            &mut self,
            request: impl tonic::IntoRequest<super::GetCaCertRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetCaCertResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rbac.v1.RbacService/GetCACert",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rbac.v1.RbacService", "GetCACert"));
            self.inner.unary(req, path, codec).await
        }
        /// Enforce reports whether subject can reach target (HTTP POST /v1/enforce).
        pub async fn enforce(
            &mut self,
            request: impl tonic::IntoRequest<super::EnforceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::EnforceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rbac.v1.RbacService/Enforce",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rbac.v1.RbacService", "Enforce"));
            self.inner.unary(req, path, codec).await
        }
        /// Reachable lists every node subject can reach, including itself
        /// (HTTP GET /v1/reachable).
        pub async fn reachable(
            &mut self,
            request: impl tonic::IntoRequest<super::ReachableRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReachableResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rbac.v1.RbacService/Reachable",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rbac.v1.RbacService", "Reachable"));
            self.inner.unary(req, path, codec).await
        }
        /// ListBindings returns all bindings (HTTP GET /v1/bindings with no query).
        pub async fn list_bindings(
            &mut self,
            request: impl tonic::IntoRequest<super::ListBindingsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListBindingsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rbac.v1.RbacService/ListBindings",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rbac.v1.RbacService", "ListBindings"));
            self.inner.unary(req, path, codec).await
        }
        /// GetBinding fetches one binding by (src, dst, scenario)
        /// (HTTP GET /v1/bindings?src&dst&scenario).
        pub async fn get_binding(
            &mut self,
            request: impl tonic::IntoRequest<super::GetBindingRequest>,
        ) -> std::result::Result<tonic::Response<super::Binding>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rbac.v1.RbacService/GetBinding",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rbac.v1.RbacService", "GetBinding"));
            self.inner.unary(req, path, codec).await
        }
        /// AddBinding creates a binding (HTTP POST /v1/bindings).
        /// ALREADY_EXISTS on duplicate.
        pub async fn add_binding(
            &mut self,
            request: impl tonic::IntoRequest<super::Binding>,
        ) -> std::result::Result<tonic::Response<super::Binding>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rbac.v1.RbacService/AddBinding",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rbac.v1.RbacService", "AddBinding"));
            self.inner.unary(req, path, codec).await
        }
        /// UpdateBinding replaces an existing binding (HTTP PUT /v1/bindings).
        /// NOT_FOUND if absent (does not create).
        pub async fn update_binding(
            &mut self,
            request: impl tonic::IntoRequest<super::Binding>,
        ) -> std::result::Result<tonic::Response<super::Binding>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rbac.v1.RbacService/UpdateBinding",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rbac.v1.RbacService", "UpdateBinding"));
            self.inner.unary(req, path, codec).await
        }
        /// SetEnabled toggles a binding's enabled flag
        /// (HTTP PATCH /v1/bindings/enabled).
        pub async fn set_enabled(
            &mut self,
            request: impl tonic::IntoRequest<super::SetEnabledRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetEnabledResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rbac.v1.RbacService/SetEnabled",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rbac.v1.RbacService", "SetEnabled"));
            self.inner.unary(req, path, codec).await
        }
        /// RemoveBinding deletes a binding (HTTP DELETE /v1/bindings).
        pub async fn remove_binding(
            &mut self,
            request: impl tonic::IntoRequest<super::RemoveBindingRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveBindingResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/rbac.v1.RbacService/RemoveBinding",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("rbac.v1.RbacService", "RemoveBinding"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod rbac_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with RbacServiceServer.
    #[async_trait]
    pub trait RbacService: std::marker::Send + std::marker::Sync + 'static {
        /// Health checks liveness. Returns FAILED_PRECONDITION when the service is
        /// paused (HTTP GET /healthz → 503). Transport failures use UNAVAILABLE and
        /// must not be confused with pause.
        async fn health(
            &self,
            request: tonic::Request<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status>;
        /// GetCACert returns the PEM-encoded CA certificate (HTTP GET /v1/ca-cert).
        async fn get_ca_cert(
            &self,
            request: tonic::Request<super::GetCaCertRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetCaCertResponse>,
            tonic::Status,
        >;
        /// Enforce reports whether subject can reach target (HTTP POST /v1/enforce).
        async fn enforce(
            &self,
            request: tonic::Request<super::EnforceRequest>,
        ) -> std::result::Result<tonic::Response<super::EnforceResponse>, tonic::Status>;
        /// Reachable lists every node subject can reach, including itself
        /// (HTTP GET /v1/reachable).
        async fn reachable(
            &self,
            request: tonic::Request<super::ReachableRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ReachableResponse>,
            tonic::Status,
        >;
        /// ListBindings returns all bindings (HTTP GET /v1/bindings with no query).
        async fn list_bindings(
            &self,
            request: tonic::Request<super::ListBindingsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListBindingsResponse>,
            tonic::Status,
        >;
        /// GetBinding fetches one binding by (src, dst, scenario)
        /// (HTTP GET /v1/bindings?src&dst&scenario).
        async fn get_binding(
            &self,
            request: tonic::Request<super::GetBindingRequest>,
        ) -> std::result::Result<tonic::Response<super::Binding>, tonic::Status>;
        /// AddBinding creates a binding (HTTP POST /v1/bindings).
        /// ALREADY_EXISTS on duplicate.
        async fn add_binding(
            &self,
            request: tonic::Request<super::Binding>,
        ) -> std::result::Result<tonic::Response<super::Binding>, tonic::Status>;
        /// UpdateBinding replaces an existing binding (HTTP PUT /v1/bindings).
        /// NOT_FOUND if absent (does not create).
        async fn update_binding(
            &self,
            request: tonic::Request<super::Binding>,
        ) -> std::result::Result<tonic::Response<super::Binding>, tonic::Status>;
        /// SetEnabled toggles a binding's enabled flag
        /// (HTTP PATCH /v1/bindings/enabled).
        async fn set_enabled(
            &self,
            request: tonic::Request<super::SetEnabledRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetEnabledResponse>,
            tonic::Status,
        >;
        /// RemoveBinding deletes a binding (HTTP DELETE /v1/bindings).
        async fn remove_binding(
            &self,
            request: tonic::Request<super::RemoveBindingRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveBindingResponse>,
            tonic::Status,
        >;
    }
    /// RbacService mirrors the HTTP /v1 REST API (plus /healthz and /v1/ca-cert).
    #[derive(Debug)]
    pub struct RbacServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> RbacServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for RbacServiceServer<T>
    where
        T: RbacService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/rbac.v1.RbacService/Health" => {
                    #[allow(non_camel_case_types)]
                    struct HealthSvc<T: RbacService>(pub Arc<T>);
                    impl<
                        T: RbacService,
                    > tonic::server::UnaryService<super::HealthRequest>
                    for HealthSvc<T> {
                        type Response = super::HealthResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RbacService>::health(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rbac.v1.RbacService/GetCACert" => {
                    #[allow(non_camel_case_types)]
                    struct GetCACertSvc<T: RbacService>(pub Arc<T>);
                    impl<
                        T: RbacService,
                    > tonic::server::UnaryService<super::GetCaCertRequest>
                    for GetCACertSvc<T> {
                        type Response = super::GetCaCertResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetCaCertRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RbacService>::get_ca_cert(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetCACertSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rbac.v1.RbacService/Enforce" => {
                    #[allow(non_camel_case_types)]
                    struct EnforceSvc<T: RbacService>(pub Arc<T>);
                    impl<
                        T: RbacService,
                    > tonic::server::UnaryService<super::EnforceRequest>
                    for EnforceSvc<T> {
                        type Response = super::EnforceResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EnforceRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RbacService>::enforce(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = EnforceSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rbac.v1.RbacService/Reachable" => {
                    #[allow(non_camel_case_types)]
                    struct ReachableSvc<T: RbacService>(pub Arc<T>);
                    impl<
                        T: RbacService,
                    > tonic::server::UnaryService<super::ReachableRequest>
                    for ReachableSvc<T> {
                        type Response = super::ReachableResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ReachableRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RbacService>::reachable(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ReachableSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rbac.v1.RbacService/ListBindings" => {
                    #[allow(non_camel_case_types)]
                    struct ListBindingsSvc<T: RbacService>(pub Arc<T>);
                    impl<
                        T: RbacService,
                    > tonic::server::UnaryService<super::ListBindingsRequest>
                    for ListBindingsSvc<T> {
                        type Response = super::ListBindingsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListBindingsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RbacService>::list_bindings(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListBindingsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rbac.v1.RbacService/GetBinding" => {
                    #[allow(non_camel_case_types)]
                    struct GetBindingSvc<T: RbacService>(pub Arc<T>);
                    impl<
                        T: RbacService,
                    > tonic::server::UnaryService<super::GetBindingRequest>
                    for GetBindingSvc<T> {
                        type Response = super::Binding;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetBindingRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RbacService>::get_binding(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetBindingSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rbac.v1.RbacService/AddBinding" => {
                    #[allow(non_camel_case_types)]
                    struct AddBindingSvc<T: RbacService>(pub Arc<T>);
                    impl<T: RbacService> tonic::server::UnaryService<super::Binding>
                    for AddBindingSvc<T> {
                        type Response = super::Binding;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Binding>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RbacService>::add_binding(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AddBindingSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rbac.v1.RbacService/UpdateBinding" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateBindingSvc<T: RbacService>(pub Arc<T>);
                    impl<T: RbacService> tonic::server::UnaryService<super::Binding>
                    for UpdateBindingSvc<T> {
                        type Response = super::Binding;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Binding>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RbacService>::update_binding(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateBindingSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rbac.v1.RbacService/SetEnabled" => {
                    #[allow(non_camel_case_types)]
                    struct SetEnabledSvc<T: RbacService>(pub Arc<T>);
                    impl<
                        T: RbacService,
                    > tonic::server::UnaryService<super::SetEnabledRequest>
                    for SetEnabledSvc<T> {
                        type Response = super::SetEnabledResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SetEnabledRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RbacService>::set_enabled(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SetEnabledSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/rbac.v1.RbacService/RemoveBinding" => {
                    #[allow(non_camel_case_types)]
                    struct RemoveBindingSvc<T: RbacService>(pub Arc<T>);
                    impl<
                        T: RbacService,
                    > tonic::server::UnaryService<super::RemoveBindingRequest>
                    for RemoveBindingSvc<T> {
                        type Response = super::RemoveBindingResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RemoveBindingRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as RbacService>::remove_binding(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RemoveBindingSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for RbacServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "rbac.v1.RbacService";
    impl<T> tonic::server::NamedService for RbacServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
