// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: rbac/v1/rbac.proto

package rbacv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RbacService_Health_FullMethodName        = "/rbac.v1.RbacService/Health"
	RbacService_GetCACert_FullMethodName     = "/rbac.v1.RbacService/GetCACert"
	RbacService_Enforce_FullMethodName       = "/rbac.v1.RbacService/Enforce"
	RbacService_Reachable_FullMethodName     = "/rbac.v1.RbacService/Reachable"
	RbacService_ListBindings_FullMethodName  = "/rbac.v1.RbacService/ListBindings"
	RbacService_GetBinding_FullMethodName    = "/rbac.v1.RbacService/GetBinding"
	RbacService_AddBinding_FullMethodName    = "/rbac.v1.RbacService/AddBinding"
	RbacService_UpdateBinding_FullMethodName = "/rbac.v1.RbacService/UpdateBinding"
	RbacService_SetEnabled_FullMethodName    = "/rbac.v1.RbacService/SetEnabled"
	RbacService_RemoveBinding_FullMethodName = "/rbac.v1.RbacService/RemoveBinding"
)

// RbacServiceClient is the client API for RbacService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RbacService mirrors the HTTP /v1 REST API (plus /healthz and /v1/ca-cert).
type RbacServiceClient interface {
	// Health checks liveness. Returns FAILED_PRECONDITION when the service is
	// paused (HTTP GET /healthz → 503). Transport failures use UNAVAILABLE and
	// must not be confused with pause.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// GetCACert returns the PEM-encoded CA certificate (HTTP GET /v1/ca-cert).
	GetCACert(ctx context.Context, in *GetCACertRequest, opts ...grpc.CallOption) (*GetCACertResponse, error)
	// Enforce reports whether subject can reach target (HTTP POST /v1/enforce).
	Enforce(ctx context.Context, in *EnforceRequest, opts ...grpc.CallOption) (*EnforceResponse, error)
	// Reachable lists every node subject can reach, including itself
	// (HTTP GET /v1/reachable).
	Reachable(ctx context.Context, in *ReachableRequest, opts ...grpc.CallOption) (*ReachableResponse, error)
	// ListBindings returns all bindings (HTTP GET /v1/bindings with no query).
	ListBindings(ctx context.Context, in *ListBindingsRequest, opts ...grpc.CallOption) (*ListBindingsResponse, error)
	// GetBinding fetches one binding by (src, dst, scenario)
	// (HTTP GET /v1/bindings?src&dst&scenario).
	GetBinding(ctx context.Context, in *GetBindingRequest, opts ...grpc.CallOption) (*Binding, error)
	// AddBinding creates a binding (HTTP POST /v1/bindings).
	// ALREADY_EXISTS on duplicate.
	AddBinding(ctx context.Context, in *Binding, opts ...grpc.CallOption) (*Binding, error)
	// UpdateBinding replaces an existing binding (HTTP PUT /v1/bindings).
	// NOT_FOUND if absent (does not create).
	UpdateBinding(ctx context.Context, in *Binding, opts ...grpc.CallOption) (*Binding, error)
	// SetEnabled toggles a binding's enabled flag
	// (HTTP PATCH /v1/bindings/enabled).
	SetEnabled(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*SetEnabledResponse, error)
	// RemoveBinding deletes a binding (HTTP DELETE /v1/bindings).
	RemoveBinding(ctx context.Context, in *RemoveBindingRequest, opts ...grpc.CallOption) (*RemoveBindingResponse, error)
}

type rbacServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRbacServiceClient(cc grpc.ClientConnInterface) RbacServiceClient {
	return &rbacServiceClient{cc}
}

func (c *rbacServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, RbacService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rbacServiceClient) GetCACert(ctx context.Context, in *GetCACertRequest, opts ...grpc.CallOption) (*GetCACertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCACertResponse)
	err := c.cc.Invoke(ctx, RbacService_GetCACert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rbacServiceClient) Enforce(ctx context.Context, in *EnforceRequest, opts ...grpc.CallOption) (*EnforceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnforceResponse)
	err := c.cc.Invoke(ctx, RbacService_Enforce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rbacServiceClient) Reachable(ctx context.Context, in *ReachableRequest, opts ...grpc.CallOption) (*ReachableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReachableResponse)
	err := c.cc.Invoke(ctx, RbacService_Reachable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rbacServiceClient) ListBindings(ctx context.Context, in *ListBindingsRequest, opts ...grpc.CallOption) (*ListBindingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBindingsResponse)
	err := c.cc.Invoke(ctx, RbacService_ListBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rbacServiceClient) GetBinding(ctx context.Context, in *GetBindingRequest, opts ...grpc.CallOption) (*Binding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Binding)
	err := c.cc.Invoke(ctx, RbacService_GetBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rbacServiceClient) AddBinding(ctx context.Context, in *Binding, opts ...grpc.CallOption) (*Binding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Binding)
	err := c.cc.Invoke(ctx, RbacService_AddBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rbacServiceClient) UpdateBinding(ctx context.Context, in *Binding, opts ...grpc.CallOption) (*Binding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Binding)
	err := c.cc.Invoke(ctx, RbacService_UpdateBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rbacServiceClient) SetEnabled(ctx context.Context, in *SetEnabledRequest, opts ...grpc.CallOption) (*SetEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetEnabledResponse)
	err := c.cc.Invoke(ctx, RbacService_SetEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rbacServiceClient) RemoveBinding(ctx context.Context, in *RemoveBindingRequest, opts ...grpc.CallOption) (*RemoveBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveBindingResponse)
	err := c.cc.Invoke(ctx, RbacService_RemoveBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RbacServiceServer is the server API for RbacService service.
// All implementations must embed UnimplementedRbacServiceServer
// for forward compatibility.
//
// RbacService mirrors the HTTP /v1 REST API (plus /healthz and /v1/ca-cert).
type RbacServiceServer interface {
	// Health checks liveness. Returns FAILED_PRECONDITION when the service is
	// paused (HTTP GET /healthz → 503). Transport failures use UNAVAILABLE and
	// must not be confused with pause.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// GetCACert returns the PEM-encoded CA certificate (HTTP GET /v1/ca-cert).
	GetCACert(context.Context, *GetCACertRequest) (*GetCACertResponse, error)
	// Enforce reports whether subject can reach target (HTTP POST /v1/enforce).
	Enforce(context.Context, *EnforceRequest) (*EnforceResponse, error)
	// Reachable lists every node subject can reach, including itself
	// (HTTP GET /v1/reachable).
	Reachable(context.Context, *ReachableRequest) (*ReachableResponse, error)
	// ListBindings returns all bindings (HTTP GET /v1/bindings with no query).
	ListBindings(context.Context, *ListBindingsRequest) (*ListBindingsResponse, error)
	// GetBinding fetches one binding by (src, dst, scenario)
	// (HTTP GET /v1/bindings?src&dst&scenario).
	GetBinding(context.Context, *GetBindingRequest) (*Binding, error)
	// AddBinding creates a binding (HTTP POST /v1/bindings).
	// ALREADY_EXISTS on duplicate.
	AddBinding(context.Context, *Binding) (*Binding, error)
	// UpdateBinding replaces an existing binding (HTTP PUT /v1/bindings).
	// NOT_FOUND if absent (does not create).
	UpdateBinding(context.Context, *Binding) (*Binding, error)
	// SetEnabled toggles a binding's enabled flag
	// (HTTP PATCH /v1/bindings/enabled).
	SetEnabled(context.Context, *SetEnabledRequest) (*SetEnabledResponse, error)
	// RemoveBinding deletes a binding (HTTP DELETE /v1/bindings).
	RemoveBinding(context.Context, *RemoveBindingRequest) (*RemoveBindingResponse, error)
	mustEmbedUnimplementedRbacServiceServer()
}

// UnimplementedRbacServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRbacServiceServer struct{}

func (UnimplementedRbacServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRbacServiceServer) GetCACert(context.Context, *GetCACertRequest) (*GetCACertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCACert not implemented")
}
func (UnimplementedRbacServiceServer) Enforce(context.Context, *EnforceRequest) (*EnforceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enforce not implemented")
}
func (UnimplementedRbacServiceServer) Reachable(context.Context, *ReachableRequest) (*ReachableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reachable not implemented")
}
func (UnimplementedRbacServiceServer) ListBindings(context.Context, *ListBindingsRequest) (*ListBindingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBindings not implemented")
}
func (UnimplementedRbacServiceServer) GetBinding(context.Context, *GetBindingRequest) (*Binding, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBinding not implemented")
}
func (UnimplementedRbacServiceServer) AddBinding(context.Context, *Binding) (*Binding, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBinding not implemented")
}
func (UnimplementedRbacServiceServer) UpdateBinding(context.Context, *Binding) (*Binding, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBinding not implemented")
}
func (UnimplementedRbacServiceServer) SetEnabled(context.Context, *SetEnabledRequest) (*SetEnabledResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetEnabled not implemented")
}
func (UnimplementedRbacServiceServer) RemoveBinding(context.Context, *RemoveBindingRequest) (*RemoveBindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBinding not implemented")
}
func (UnimplementedRbacServiceServer) mustEmbedUnimplementedRbacServiceServer() {}
func (UnimplementedRbacServiceServer) testEmbeddedByValue()                     {}

// UnsafeRbacServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RbacServiceServer will
// result in compilation errors.
type UnsafeRbacServiceServer interface {
	mustEmbedUnimplementedRbacServiceServer()
}

func RegisterRbacServiceServer(s grpc.ServiceRegistrar, srv RbacServiceServer) {
	// If the following call panics, it indicates UnimplementedRbacServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RbacService_ServiceDesc, srv)
}

func _RbacService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RbacServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RbacService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RbacServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RbacService_GetCACert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCACertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RbacServiceServer).GetCACert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RbacService_GetCACert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RbacServiceServer).GetCACert(ctx, req.(*GetCACertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RbacService_Enforce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnforceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RbacServiceServer).Enforce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RbacService_Enforce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RbacServiceServer).Enforce(ctx, req.(*EnforceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RbacService_Reachable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReachableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RbacServiceServer).Reachable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RbacService_Reachable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RbacServiceServer).Reachable(ctx, req.(*ReachableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RbacService_ListBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RbacServiceServer).ListBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RbacService_ListBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RbacServiceServer).ListBindings(ctx, req.(*ListBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RbacService_GetBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RbacServiceServer).GetBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RbacService_GetBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RbacServiceServer).GetBinding(ctx, req.(*GetBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RbacService_AddBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Binding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RbacServiceServer).AddBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RbacService_AddBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RbacServiceServer).AddBinding(ctx, req.(*Binding))
	}
	return interceptor(ctx, in, info, handler)
}

func _RbacService_UpdateBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Binding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RbacServiceServer).UpdateBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RbacService_UpdateBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RbacServiceServer).UpdateBinding(ctx, req.(*Binding))
	}
	return interceptor(ctx, in, info, handler)
}

func _RbacService_SetEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RbacServiceServer).SetEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RbacService_SetEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RbacServiceServer).SetEnabled(ctx, req.(*SetEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RbacService_RemoveBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RbacServiceServer).RemoveBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RbacService_RemoveBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RbacServiceServer).RemoveBinding(ctx, req.(*RemoveBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RbacService_ServiceDesc is the grpc.ServiceDesc for RbacService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RbacService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rbac.v1.RbacService",
	HandlerType: (*RbacServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _RbacService_Health_Handler,
		},
		{
			MethodName: "GetCACert",
			Handler:    _RbacService_GetCACert_Handler,
		},
		{
			MethodName: "Enforce",
			Handler:    _RbacService_Enforce_Handler,
		},
		{
			MethodName: "Reachable",
			Handler:    _RbacService_Reachable_Handler,
		},
		{
			MethodName: "ListBindings",
			Handler:    _RbacService_ListBindings_Handler,
		},
		{
			MethodName: "GetBinding",
			Handler:    _RbacService_GetBinding_Handler,
		},
		{
			MethodName: "AddBinding",
			Handler:    _RbacService_AddBinding_Handler,
		},
		{
			MethodName: "UpdateBinding",
			Handler:    _RbacService_UpdateBinding_Handler,
		},
		{
			MethodName: "SetEnabled",
			Handler:    _RbacService_SetEnabled_Handler,
		},
		{
			MethodName: "RemoveBinding",
			Handler:    _RbacService_RemoveBinding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rbac/v1/rbac.proto",
}
